### ISSUE TITLE
Bot notifications need updating

### ISSUE THREAD

**Issue by Alcaro** [TheGreekBrit/YoshiDis#3]
I enabled mandatory SSL on my server recently. GitHub refuses to follow redirects, so the bot notifications are broken. To fix, someone with the relevant access needs to do the following:
- Go to https://github.com/TheGreekBrit/YoshiDis/settings/hooks (if you don't have access, it will 404)
- Follow the link labeled http://floating.muncher.se/bot/connect/github.php
- Change payload URL to https://floating.muncher.se/bot/connect/github.php (change http:// to https://).

GitHub will also throw a notice about verifying SSL certificates. Don't click it, leave verification on.

**Comment by ahoustonpsych** [comment]
Fixed! Thanks for the heads up!

**Comment by uFrost** [comment]
I feel like this wasn't meant for me to see...

**Comment by Alcaro** [comment]
Public issue was the only contact method I could find that wasn't three months inactive. Something less public would be better, but delivering the message to the right person is more important than not delivering it to irrelevant users.

Issues you don't care about happen if you're watching a repo. I get a bunch too. No big deal, just ignore them, or unsubscribe if they're too noisy (for example if there's someone who points out that they have nothing to do with this issue).

**Comment by uFrost** [comment]
Oh, my bad. Thanks for the info!
